# Generated by Django 2.2.1 on 2019-05-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catDecription',
            new_name='catDescription',
        ),
    ]
