# Generated by Django 2.2.1 on 2019-05-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_category_catkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artName', models.CharField(max_length=200)),
                ('artCotent', models.TextField()),
                ('artAuthor', models.CharField(max_length=100)),
                ('artDateCreate', models.DateTimeField(auto_now=True)),
                ('artDesImg', models.CharField(max_length=255)),
                ('artCatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Category')),
            ],
        ),
    ]
