# Generated by Django 2.2.1 on 2019-05-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artCotent',
            new_name='artContent',
        ),
    ]
