# Generated by Django 2.2.1 on 2019-05-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0005_auto_20190514_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Category', verbose_name='catName'),
        ),
    ]
