# Generated by Django 2.2.1 on 2019-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0009_auto_20190514_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artView',
            field=models.IntegerField(default=0),
        ),
    ]
